# Generated by Django 3.2.12 on 2022-02-17 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名前')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='曲名')),
                ('lyrics', models.TextField(verbose_name='歌詞')),
                ('composer', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, related_name='composer', to='app.artist')),
                ('lyrist', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, related_name='lyrist', to='app.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.song')),
            ],
        ),
    ]
