# Generated by Django 3.2.12 on 2022-02-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='曲名')),
                ('composer', models.CharField(max_length=32, verbose_name='作曲者')),
                ('lyrist', models.CharField(max_length=32, verbose_name='作詞者')),
                ('lyrics', models.TextField(verbose_name='歌詞')),
            ],
        ),
    ]
