# Generated by Django 3.2.12 on 2022-02-17 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名前')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default='', max_length=32, on_delete=django.db.models.deletion.PROTECT, to='app.artist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=32, verbose_name='アーティスト名'),
        ),
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.PROTECT, related_name='composer', to='app.person'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrist',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.PROTECT, related_name='lyrist', to='app.person'),
        ),
    ]
