# Generated by Django 3.2.12 on 2022-02-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.song'),
        ),
    ]
