# Generated by Django 3.2.12 on 2022-02-17 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220217_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.PROTECT, to='app.artist', verbose_name='アーティスト'),
        ),
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.PROTECT, related_name='composer', to='app.person', verbose_name='作曲者'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrist',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.PROTECT, related_name='lyrist', to='app.person', verbose_name='作詞者'),
        ),
    ]
